MySchool/Models/ErrorViewModel.cs
namespace MySchool.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MySchool/Controllers/GuardianController.cs
using Microsoft.AspNetCore.Mvc;
using MySchool.Core.Application.Dtos;
using MySchool.Core.Application.Interfaces.Services;

namespace MySchool.Controllers
{
    public class GuardianController : Controller
    {
        private readonly IGuardianService _guardianService;
        public GuardianController(IGuardianService guardianService)
        {
            _guardianService = guardianService;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(GuardianRequest model)
        {
            var response = _guardianService.Create(model);
            if(response == null)
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Details(string id)
        {
            var response = _guardianService.Get(id);
            if(response == null)
            {
                return RedirectToAction("Guardians");
            }
            return View(response.Data);
        }

        public IActionResult Guardians()
        {
            var response = _guardianService.GetAll();
            return View(response.Data);
        }
    }
}

MySchool/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MySchool.Models;
using System.Diagnostics;

namespace MySchool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MySchool/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using MySchool.Core.Application.Dtos;
using MySchool.Core.Application.Interfaces.Services;

namespace MySchool.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService) 
        { 
            _userService = userService;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginRequest request)
        {
            var response = _userService.Login(request);
            if(!response.Status)
            {
                return View();
            }
            if (response.Data.Roles.Select(a => a.Name).Contains("SuperAdmin"))
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

MySchool/Views/Guardian/Details.cshtml
@model MySchool.Core.Application.Dtos.GuardianDto
@{
}

<h1>@Model.FullName Details</h1>
<h5>Email:</h5> <p>@Model.Email</p>
<h5>Phone:</h5> <p>@Model.PhoneNumber</p>

MySchool/Views/Guardian/Guardians.cshtml
@model List<MySchool.Core.Application.Dtos.GuardianDto>
@{
}

<h2>List of Guardians</h2>

<table>
    <thead>
        <tr>
            <th>FullName</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Actions</th>

        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.FullName</td>
                <td>@item.Email</td>
                <td>@item.PhoneNumber</td>
                <td>
                    <button><a asp-action="Details" asp-route-id ="@item.Id">Details</a></button>
                    <button>Delete</button>
                </td>
            </tr>
        }
        
    </tbody>
</table>

MySchool/Views/Guardian/Register.cshtml
@using MySchool.Core.Domain.Enums
@model MySchool.Core.Application.Dtos.GuardianRequest
@{

}

<h1>Register Guardian</h1>

<form method="post" enctype="multipart/form-data">
    <div>
        <label>Email</label>
        <input type="email" name="Email" placeholder="enter your email" />
    </div>
    <div>
        <label>Password</label>
        <input type="password" name="Password" placeholder="enter your password" />
    </div>
    <div>
        <label>Confirm Password</label>
        <input type="password" name="ConfirmPassword" placeholder="confirm your password" />
    </div>
    <div>
        <label>First Name</label>
        <input type="text" name="FirstName" placeholder="enter your first name" />
    </div>
    <div>
        <label>Last Name</label>
        <input type="text" name="LastName" placeholder="enter your last name" />
    </div>
    <div>
        <label>Dob</label>
        <input type="date" name="DateOfBirth" />
    </div>
    <div>
        <label>Gender</label>
        <select asp-for="Gender"  asp-items="@Html.GetEnumSelectList(typeof(Gender)) "></select>
    </div>
    <div>
        <label>PhoneNumber</label>
        <input type="text" name="PhoneNumber" placeholder="enter your phone number" />
    </div>

    <div>
        <label>Image</label>
        <input type="file" name="ImageUrl" />
    </div>

    <div>
        <input type="submit" value="Create" />
    </div>
    
</form>

       

MySchool/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MySchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MySchool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MySchool.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MySchool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Guardian" asp-action="Register">Create Guardian</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Guardian" asp-action="Guardians">Guardians</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MySchool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>